using Microsoft.Xna.Framework;
using StardewMod.Models;

namespace StardewMod.Services.ScheduleRouting;

/// <summary>
/// 供编辑器预览与运行时编译共用的路线预览结果。
/// 会保留每张地图上的分段信息，方便 UI 按颜色叠加绘制。
/// </summary>
internal sealed class CompiledRoutePreview
{
    public List<CompiledRoutePreviewSegment> Segments { get; } = new();

    public bool HasAnyPoints => this.Segments.Any(segment => segment.Tiles.Count > 0);

    public void AppendSegment(string locationName, IReadOnlyList<Point> points, bool isAutoGenerated)
    {
        if (string.IsNullOrWhiteSpace(locationName) || points.Count == 0)
        {
            return;
        }

        CompiledRoutePreviewSegment? targetSegment = this.Segments.LastOrDefault();
        if (targetSegment is null ||
            !string.Equals(targetSegment.LocationName, locationName, StringComparison.OrdinalIgnoreCase) ||
            targetSegment.IsAutoGenerated != isAutoGenerated)
        {
            targetSegment = new CompiledRoutePreviewSegment(locationName, isAutoGenerated);
            this.Segments.Add(targetSegment);
        }

        foreach (Point point in points)
        {
            targetSegment.Append(point);
        }
    }

    public List<Point> FlattenPoints()
    {
        List<Point> merged = new();
        foreach (CompiledRoutePreviewSegment segment in this.Segments)
        {
            foreach (TilePointData tile in segment.Tiles)
            {
                Point point = tile.ToPoint();
                if (merged.Count > 0 && merged[^1] == point)
                {
                    continue;
                }

                merged.Add(point);
            }
        }

        return merged;
    }
}

internal sealed class CompiledRoutePreviewSegment
{
    public CompiledRoutePreviewSegment(string locationName, bool isAutoGenerated)
    {
        this.LocationName = locationName;
        this.IsAutoGenerated = isAutoGenerated;
    }

    public string LocationName { get; }

    public bool IsAutoGenerated { get; }

    public List<TilePointData> Tiles { get; } = new();

    public void Append(Point point)
    {
        if (this.Tiles.Count > 0)
        {
            TilePointData last = this.Tiles[^1];
            if (last.X == point.X && last.Y == point.Y)
            {
                return;
            }
        }

        this.Tiles.Add(new TilePointData(point));
    }
}
