using Microsoft.Xna.Framework;
using StardewValley;
using StardewValley.Pathfinding;

namespace StardewMod.Services.ScheduleRouting;

/// <summary>
/// 编译跨地图自动桥接路径。
/// 这里优先复用原版地图级路由，在 Farm 参与时仅补本模组自己的定向桥接。
/// </summary>
internal sealed class NpcScheduleRouteBridgeService
{
    private readonly FarmLocationRouteResolver farmLocationRouteResolver;

    public NpcScheduleRouteBridgeService(FarmLocationRouteResolver farmLocationRouteResolver)
    {
        this.farmLocationRouteResolver = farmLocationRouteResolver;
    }

    public List<Point> TryBuildRoutePoints(NPC npc, string ruleKey, string startLocation, Point startTile, string endLocation, Point endTile)
    {
        return this.TryBuildRoutePreview(npc, startLocation, startTile, endLocation, endTile).FlattenPoints();
    }

    public CompiledRoutePreview TryBuildRoutePreview(NPC npc, string startLocation, Point startTile, string endLocation, Point endTile)
    {
        if (string.IsNullOrWhiteSpace(startLocation) ||
            string.IsNullOrWhiteSpace(endLocation) ||
            startTile == Point.Zero ||
            endTile == Point.Zero)
        {
            return new CompiledRoutePreview();
        }

        if (string.Equals(startLocation, endLocation, StringComparison.OrdinalIgnoreCase))
        {
            CompiledRoutePreview preview = new();
            preview.AppendSegment(startLocation, this.BuildSingleLocationSegment(startLocation, startTile, endTile, npc), isAutoGenerated: true);
            return preview;
        }

        string[]? locationRoute = this.ResolveLocationRoute(npc, startLocation, endLocation);
        if (locationRoute is null || locationRoute.Length == 0)
        {
            return new CompiledRoutePreview();
        }

        return this.BuildCrossLocationSegments(npc, locationRoute, startTile, endTile);
    }

    private string[]? ResolveLocationRoute(NPC npc, string startLocation, string endLocation)
    {
        if (this.farmLocationRouteResolver.TryResolveRoute(startLocation, endLocation, npc.Gender, out string[] farmRoute))
        {
            return farmRoute;
        }

        return WarpPathfindingCache.GetLocationRoute(startLocation, endLocation, npc.Gender);
    }

    private CompiledRoutePreview BuildCrossLocationSegments(NPC npc, IReadOnlyList<string> locationRoute, Point startTile, Point endTile)
    {
        CompiledRoutePreview preview = new();
        Point locationStartPoint = startTile;
        for (int i = 0; i < locationRoute.Count; i++)
        {
            string currentLocationName = locationRoute[i];
            GameLocation currentLocation = ResolveLiveLocation(currentLocationName);
            if (i < locationRoute.Count - 1)
            {
                string nextLocationName = locationRoute[i + 1];
                Point warpPoint = currentLocation.getWarpPointTo(nextLocationName, npc);
                if (warpPoint == Point.Zero)
                {
                    return new CompiledRoutePreview();
                }

                List<Point> segment = this.BuildSegment(currentLocation, locationStartPoint, warpPoint, npc);
                if (segment.Count == 0)
                {
                    return new CompiledRoutePreview();
                }

                preview.AppendSegment(currentLocationName, segment, isAutoGenerated: true);
                locationStartPoint = currentLocation.getWarpPointTarget(warpPoint, npc);
            }
            else
            {
                List<Point> segment = this.BuildSegment(currentLocation, locationStartPoint, endTile, npc);
                if (segment.Count == 0)
                {
                    return new CompiledRoutePreview();
                }

                preview.AppendSegment(currentLocationName, segment, isAutoGenerated: true);
            }
        }

        return preview;
    }

    private List<Point> BuildSingleLocationSegment(string locationName, Point startTile, Point endTile, NPC npc)
    {
        GameLocation location = ResolveLiveLocation(locationName);
        return this.BuildSegment(location, startTile, endTile, npc);
    }

    private List<Point> BuildSegment(GameLocation location, Point startTile, Point endTile, NPC npc)
    {
        Stack<Point>? path = PathFindController.findPathForNPCSchedules(startTile, endTile, location, 30000, npc);
        return path?.ToList() ?? new List<Point>();
    }
    private static GameLocation ResolveLiveLocation(string canonicalLocationName)
    {
        string liveLocationName = canonicalLocationName;
        foreach (string activePassiveFestival in Game1.netWorldState.Value.ActivePassiveFestivals)
        {
            if (Utility.TryGetPassiveFestivalData(activePassiveFestival, out var data) &&
                data.MapReplacements is not null &&
                data.MapReplacements.TryGetValue(liveLocationName, out string? replacedName))
            {
                liveLocationName = replacedName;
                break;
            }
        }

        GameLocation currentLocation = Game1.RequireLocation(liveLocationName);
        if (currentLocation.Name.Equals("Trailer", StringComparison.Ordinal) &&
            Game1.MasterPlayer.mailReceived.Contains("pamHouseUpgrade"))
        {
            currentLocation = Game1.RequireLocation("Trailer_Big");
        }

        return currentLocation;
    }
}
